# Generated by Django 3.2.3 on 2023-05-17 02:47

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='contract_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_contracts', to='gatingDB.contract')),
            ],
        ),
        migrations.CreateModel(
            name='guild',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('chainID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('httpRPC', models.URLField(blank=True, null=True)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.user')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('contracts', models.ManyToManyField(related_name='roles', through='gatingDB.contract_role', to='gatingDB.contract')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.guild')),
            ],
        ),
        migrations.AddField(
            model_name='contract_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_contracts', to='gatingDB.role'),
        ),
        migrations.AddField(
            model_name='contract',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.network'),
        ),
        migrations.CreateModel(
            name='awaitingConnection',
            fields=[
                ('message', models.TextField(primary_key=True, serialize=False)),
                ('interactionToken', models.IntegerField()),
                ('interactionAppID', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatingDB.user')),
            ],
        ),
        migrations.CreateModel(
            name='django_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatingDB.user')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('address', 'network'), name='wallet_unique_address_network'),
        ),
        migrations.AddConstraint(
            model_name='contract_role',
            constraint=models.UniqueConstraint(fields=('role', 'contract'), name='contract_role_unique_role_contract'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('address', 'network'), name='contract_unique_address_network'),
        ),
    ]
