# Generated by Django 3.2.3 on 2023-05-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatingDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
