# Generated by Django 3.2.3 on 2023-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatingDB', '0003_auto_20230521_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_role',
            options={'verbose_name_plural': 'Contracts and Roles'},
        ),
        migrations.AlterModelOptions(
            name='django_user',
            options={'verbose_name_plural': 'Django Users'},
        ),
        migrations.AddField(
            model_name='awaitingconnection',
            name='interactionID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
